#readme https://github.com/greshake/i3status-rust/blob/master/blocks.md

theme = "mikael"
icons = "awesome"

[[block]]
block = "time"
interval = 60
format = "%R %a %d/%m"
on_click = "gnome-calendar"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "sound"

[[block]]
block = "disk_space"
path = "/home/mmikaeleriksson/"
alias = "~/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0