#readme https://github.com/greshake/i3status-rust/blob/master/blocks.md

theme = "mikael"
icons = "awesome"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "disk_space"
path = "/home/mmikaeleriksson/"
alias = "~/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUg}GB"
format_swap = "{SUg}GB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}° avg"
chip = "*-isa-*"